### PR TITLE
object-key serialization of Map with BrowserCompatible feature，for issue #2183

### PR DESCRIPTION
**Pull request by rowstop**
### What this PR does / why we need it?
object-key serialization of Map with BrowserCompatible feature，for issue #2183

### Summary of your change
```json
{"[1,false,{\"name\":\"array\"}]":false}
```
#### Please indicate you've done the following:

- [ ] Made sure tests are passing and test coverage is added if needed.
- [ ] Made sure commit message follow the rule of [Conventional Commits specification](https://www.conventionalcommits.org/).
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed.

### CODE REVIEW

**Comment by rowstop** [comment]
这个地方这么处理是否合适？🤔
image

**Comment by wenshao** [comment]
这样的实现太hack了

**Comment by wenshao** [comment]
这里有转义的问题，比如key是一个Map，就会有转义问题

**Comment by wenshao** [comment]
```java
 public void writeNameAny(Object name) {
        if (startObject) {
            startObject = false;
        } else {
            writeComma();
        }

        boolean toString = (context.features & (WriteNonStringKeyAsString.mask | BrowserCompatible.mask)) != 0;
        if (toString && !(name instanceof String)) {
            if (name instanceof Temporal) {
                toString = false;
            }
        }

        if (toString) {
            String strName = JSON.toJSONString(name, context);
            char c0 = strName.length() > 0 ? strName.charAt(0) : '\0';
            if (c0 == quote) {
                writeRaw(strName);
            } else {
                writeString(strName);
            }
            return;
        }
        writeAny(name);
    }
```
比如这样的实现支持的场景更完整一些

**Comment by rowstop** [comment]
> ```java
>  public void writeNameAny(Object name) {
>         if (startObject) {
>             startObject = false;
>         } else {
>             writeComma();
>         }
> 
>         boolean toString = (context.features & (WriteNonStringKeyAsString.mask | BrowserCompatible.mask)) != 0;
>         if (toString && !(name instanceof String)) {
>             if (name instanceof Temporal) {
>                 toString = false;
>             }
>         }
> 
>         if (toString) {
>             String strName = JSON.toJSONString(name, context);
>             char c0 = strName.length() > 0 ? strName.charAt(0) : '\0';
>             if (c0 == quote) {
>                 writeRaw(strName);
>             } else {
>                 writeString(strName);
>             }
>             return;
>         }
>         writeAny(name);
>     }
> ```
> 
> 比如这样的实现支持的场景更完整一些

这样做貌似有问题，会出现非浏览器兼容的 json 格式，object key 有可能出现转义的情况，但是结果可读可转化，而且支持自定义， 不会出现非兼容格式的 json

**Comment by rowstop** [comment]
🤔。。。我再看下

**Pull request closed without merging**
