### PR TITLE
add new method JSONFactory.getDefaultReaderFeatures() ...

### PR DESCRIPTION
**Pull request by noear**
### What this PR does / why we need it?
https://github.com/alibaba/fastjson2/issues/2610

### Summary of your change
add new method JSONFactory.getDefaultReaderFeatures(),JSONFactory.getDefaultWriterFeatures()
add new method JSONFactory.getDefaultWriterZoneId(),JSONFactory.getDefaultReaderZoneId()
add new method JSONFactory.getDefaultReaderFormat()

#### Please indicate you've done the following:

- [ ] Made sure tests are passing and test coverage is added if needed.
- [ ] Made sure commit message follow the rule of [Conventional Commits specification](https://www.conventionalcommits.org/).
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed.

### CODE REVIEW

**Comment by wenshao** [comment]
需要签署CLA，同时你要在本地执行mvn validate修复code style的问题

**Comment by noear** [comment]
果然很麻烦啊。

**Comment by noear** [comment]
确实验证通不过啊。。。不适，不知道有什么 code style 的问题。

**Comment by wenshao** [comment]
不能连续空行，你看错误信息

**Comment by noear** [comment]
还真是空行。现在好了

**Comment by noear** [comment]
cla 麻烦了。要填写真实姓名。。。还是放弃了，我想保护稳私

**Pull request merged**
