### PR TITLE
Add a JSONReader.Feature that can convert empty string to null

### PR DESCRIPTION
**Pull request by rowstop**
### What this PR does / why we need it?

Add a JSONReader.Feature that can convert empty string to null ,for issue #2317 #2060

### Summary of your change
需要注意这里的实现，有些集合不支持 null，而且我觉得直接过滤 null 值也合适，我这里直接过滤了，看下这么做否合适
但是动态字节码的逻辑里并没有过滤null值，不太敢改这一块，
`FieldReaderStringField`
image

#### Please indicate you've done the following:

- [x] Made sure tests are passing and test coverage is added if needed.
- [x] Made sure commit message follow the rule of [Conventional Commits specification](https://www.conventionalcommits.org/).
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed.

### CODE REVIEW

**Comment by rowstop** [comment]
🤔又卡住了？

**Comment by wenshao** [comment]
和其他JSONReader.Feature一致，EmptyStringToNull改为EmptyStringAsNull ？

**Comment by rowstop** [comment]
> 和其他JSONReader.Feature一致，EmptyStringToNull改为EmptyStringAsNull ？

**Comment by rowstop** [comment]
> 和其他JSONReader.Feature一致，EmptyStringToNull改为EmptyStringAsNull ？

好的 看下

**Pull request merged**
