### PR TITLE
fix jsonb deserialize error on null list field ,for issue #2181

### PR DESCRIPTION
**Pull request by rowstop**
### What this PR does / why we need it?
fix jsonb deserialize error on null list field ,for issue #2181
#### Please indicate you've done the following:

- [ ] Made sure tests are passing and test coverage is added if needed.
- [ ] Made sure commit message follow the rule of [Conventional Commits specification](https://www.conventionalcommits.org/).
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed.

### CODE REVIEW

**Comment by wenshao** [comment]
可以补充testcase么？

**Comment by rowstop** [comment]
@wenshao 有冲突

**Comment by rowstop** [comment]
@wenshao 需要解决下冲突

**Comment by wenshao** [comment]
能否通过修复去掉多余空格，extends前换行等问题，不需要在pom.xml excludes的方式解决checkstyle的问题。本地执行mvn validate检验根据错误提示修改也挺方便的。

**Comment by rowstop** [comment]
> 能否通过修复去掉多余空格，extends前换行等问题，不需要在pom.xml excludes的方式解决checkstyle的问题。本地执行mvn validate检验根据错误提示修改也挺方便的。

我用了，他跟#2181 提供的testcase 就不能保持一致了，要求我用 final 修饰字段
image

**Pull request merged**
